apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: todoapp
spec:
  containers:
    - name: todoapp-pod
      image: tongobash/todoapp:3.0.0
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /api/healz/live
          port: 8000
        initialDelaySeconds: 20
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /api/healz/read
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10
  restartPolicy: Always
